name: Analy
version: '1.0.0'
main: com.mchpixel.analy.Analy
api-version: '1.21'
load: STARTUP
authors: [ Fabian_MCH ]
description: A production-grade, open-architecture analytics ecosystem that turns raw Minecraft server events into actionable insights through a generic metric pipeline, real-time dashboards, and an extensible plugin API.
commands:
  debuganaly:
    description: Toggle debugging Features
    usage: /debuganaly